### ISSUE TITLE
Update the Uuid dependency

### ISSUE THREAD

**Issue by clemortel** [Floating-Dartists/matomo-tracker#127]
Hi!

If possible, could the uuid dependency be updated from ^3.0.7 to ^4.2.1 for the next release?
Thanks! Have a good day !

**Comment by TesteurManiak** [comment]
Not sure that we can upgrade to the latest `v4.2.1`, dependencies upgrade are handled by our dependabot, if it didn't offered to upgrade from `uuid: ^4.1.0` (on main branch) it might be because another dependency is blocking it.

If `v4.1.0` is still acceptable for you, while waiting for the next release on pub.dev you can directly point to the main branch or a specific commit from your pubspec.yaml.

```yaml
dependencies:
  matomo_tracker:
    git:
      url: git@github.com:Floating-Dartists/matomo-tracker.git
      ref: main
```
