### ISSUE TITLE
Bug: Support newer uuid version

### ISSUE THREAD

**Issue by c-seeger** [Floating-Dartists/matomo-tracker#140]
**Describe the bug**
the current tagged version does not support newer uuid version. The commit that changed this is from January 30 but the last release was October 12 last year. Please create a new release tag to get this change into the latest version.

**To Reproduce**
add uuid >=4.1.0 
then try to add matomo_tracker

**Expected behavior**
works

**Comment by c-seeger** [comment]
cc: @TesteurManiak

**Comment by c-seeger** [comment]
Quick workaround for now (since the fix is in main but not in any tag):

pubspec.yaml
```
matomo_tracker:
  git:
    url: git@github.com:Floating-Dartists/matomo-tracker.git
    ref: main

```
